esphome:
  name: sen6x_arduino

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

i2c:
  sda: GPIO6
  scl: GPIO7
  id: bus_a
  scan: true

external_components:
  - source: components/sen6x

sensor:
  - platform: sen6x
    i2c_id: bus_a
    address: 0x6B
    update_interval: 10s
    model: "auto"
    temperature:
      name: "SEN6x Temperature"
    humidity:
      name: "SEN6x Humidity"
    co2:
      name: "SEN6x CO2"
    voc_index:
      name: "SEN6x VOC Index"
    nox_index:
      name: "SEN6x NOx Index"
    hcho:
      name: "SEN6x HCHO"
    pm_1_0:
      name: "PM1.0"
    pm_2_5:
      name: "PM2.5"
    pm_4_0:
      name: "PM4.0"
    pm_10_0:
      name: "PM10"
